services:
  hapi-poc-test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hapijs-test
    env_file: .env
    ports:
      - '3000:3000'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    command: node src/index.js
    networks:
      - hapi-app-test
    depends_on:
      - mongo-test

  mongo-test:
    image: mongo:latest
    container_name: mongo-test
    restart: always
    ports:
      - '27019:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - hapi-app-test

volumes:
  node_modules:
  mongo-data:

networks:
  hapi-app-test:
    driver: bridge
